defaults:
  - scope:
      path: ""
      type: "image/webp"
    values:
      cache-control: "public, max-age=3600"

defaults:
  - scope:
      path: ""
      type: "css"
    values:
      cache-control: "public, max-age=3600"

defaults:
  - scope:
      path: ""
      type: "text/javascript"
    values:
      cache-control: "public, max-age=3600"     